/* TABLE EVENTS */
export const EVENT_HEADER_CELL_UPDATED = "EVENT_HEADER_CELL_UPDATED";
export const EVENT_HEADER_CELL_CLEARED = "EVENT_HEADER_CELL_CLEARED";
export const EVENT_BODY_CELL_UPDATED = "EVENT_BODY_CELL_UPDATED";
export const EVENT_BODY_CELL_CLEARED = "EVENT_BODY_CELL_CLEARED";

export const EVENT_COLUMN_ADDED = "EVENT_COLUMN_ADDED";
export const EVENT_COLUMN_MOVED = "EVENT_COLUMN_MOVED";
export const EVENT_COLUMN_DELETED = "EVENT_COLUMN_DELETED";

export const EVENT_ROW_ADDED = "EVENT_ROW_ADDED";
export const EVENT_ROW_MOVED = "EVENT_ROW_MOVED";
export const EVENT_ROW_DELETED = "EVENT_ROW_DELETED";

/* SELECT EVENTS */
export const EVENT_SELECT_CELL_STARTED = "EVENT_SELECT_CELL_STARTED";
export const EVENT_SELECT_CELL_UPDATED = "EVENT_SELECT_CELL_UPDATED";
export const EVENT_SELECT_ROW_STARTED = "EVENT_SELECT_ROW_STARTED";
export const EVENT_SELECT_ROW_UPDATED = "EVENT_SELECT_ROW_UPDATED";
export const EVENT_SELECT_COLUMN_STARTED = "EVENT_SELECT_COLUMN_STARTED";
export const EVENT_SELECT_COLUMN_UPDATED = "EVENT_SELECT_COLUMN_UPDATED";
export const EVENT_SELECT_FINISHED = "EVENT_SELECT_FINISHED";
export const EVENT_SELECT_CLEARED = "EVENT_SELECT_CLEARED";

/* EDIT EVENTS */
export const EVENT_EDIT_CELL_STARTED = "EVENT_EDIT_CELL_STARTED";
export const EVENT_EDIT_CELL_CHANGED = "EVENT_EDIT_CELL_CHANGED";
export const EVENT_EDIT_CELL_COMMITED = "EVENT_EDIT_CELL_COMMITED";
export const EVENT_EDIT_CELL_FINISHED = "EVENT_EDIT_CELL_FINISHED";