export const EVENT_HEADER_CELL_UPDATED = "EVENT_HEADER_CELL_UPDATED";
export const EVENT_HEADER_CELL_CLEARED = "EVENT_HEADER_CELL_CLEARED";
export const EVENT_BODY_CELL_UPDATED = "EVENT_BODY_CELL_UPDATED";
export const EVENT_BODY_CELL_CLEARED = "EVENT_BODY_CELL_CLEARED";

export const EVENT_COLUMN_ADDED = "EVENT_COLUMN_ADDED";
export const EVENT_COLUMN_MOVED = "EVENT_COLUMN_MOVED";
export const EVENT_COLUMN_DELETED = "EVENT_COLUMN_DELETED";

export const EVENT_ROW_ADDED = "EVENT_ROW_ADDED";
export const EVENT_ROW_MOVED = "EVENT_ROW_MOVED";
export const EVENT_ROW_DELETED = "EVENT_ROW_DELETED";